---
name: "dante"

secrets:
  - name: protobufsrc
  - name: slack


databases:
  - name: main
    postgres:
      serverGroup: default
      dbExtensions:
        - "uuid-ossp"

      migrateContainer:
        image:
          name: dante
          registry: ghcr.io/pentops
        command: [migrate]
        envVars:
          - name: "POSTGRES_URL"
            database:
              databaseName: main


runtimes:
  - name: main

    routes:
      - prefix: "/dante/v1/*"
        protocol: ROUTE_PROTOCOL_HTTP

    namedEnvPolicies:
      - "sqs-direct"

    subscriptions:
      - name: "/o5.messaging.v1.topic.DeadMessageTopic"
        envName: "*"

    workerConfig:
      noDeadletters: true

    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
            name: dante
            registry: ghcr.io/pentops
        command: [serve]
        envVars:
          - name: POSTGRES_URL
            database:
              databaseName: main
          - name: PUBLIC_PORT
            value: "8080"
          - name: SLACK_URL
            secret:
              secretName: slack
              jsonKey: url
