---
name: "dante"

databases:
  - name: main
    postgres:
      runOutbox: true
      dbName: dante
      serverGroup: default
      dbExtensions:
        - "uuid-ossp"

      migrateContainer:
        image:
          name: dante
          registry: ghcr.io/pentops
        command: [migrate]
        envVars:
          - name: "POSTGRES_URL"
            database:
              databaseName: main


runtimes:
  - name: main
    grantMetaDeployPermissions: false

    subscriptions:
      - name: "dead-letter" # Match the name in o5 deployer

    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
            name: dante
            registry: ghcr.io/pentops
        command: [serve]
        envVars:
          - name: POSTGRES_URL
            database:
              databaseName: main
